[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "rbxtelemetry"
version = "0.1.0"
description = "Simple telemetry client for batching events"
authors = [{ name = "Ecliptorhize" }]
readme = "README.md"
requires-python = ">=3.8"
